/* config.h
 * Copyright (C) 2023 John Jekel and Nick Chan
 * See the LICENSE file at the root of the project for licensing info.
 *
 * Contains build-time configuration information for IRVE
 *
*/

#ifndef CONFIG_H
#define CONFIG_H

/* Constants And Defines */

//Build system independent

#ifndef IRVE_INTERNAL_CONFIG_BUILD_TIME_STRING
#define IRVE_INTERNAL_CONFIG_BUILD_TIME_STRING __TIME__
#endif

#ifndef IRVE_INTERNAL_CONFIG_BUILD_DATE_STRING
#define IRVE_INTERNAL_CONFIG_BUILD_DATE_STRING __DATE__
#endif

//Build system dependent

#if __has_include("cmake_config.h")
#include "cmake_config.h"

#ifndef IRVE_INTERNAL_CONFIG_DISABLE_LOGGING
#define IRVE_INTERNAL_CONFIG_DISABLE_LOGGING        IRVE_CMAKE_DISABLE_LOGGING
#endif

#ifndef IRVE_INTERNAL_CONFIG_ASYNC_LOGGING
#define IRVE_INTERNAL_CONFIG_ASYNC_LOGGING          IRVE_CMAKE_ASYNC_LOGGING
#endif

#ifndef IRVE_INTERNAL_CONFIG_SANITIZE
#define IRVE_INTERNAL_CONFIG_SANITIZE               IRVE_CMAKE_SANITIZE
#endif

#ifndef IRVE_INTERNAL_CONFIG_VERSION_MAJOR
#define IRVE_INTERNAL_CONFIG_VERSION_MAJOR          IRVE_CMAKE_VERSION_MAJOR
#endif

#ifndef IRVE_INTERNAL_CONFIG_VERSION_MINOR
#define IRVE_INTERNAL_CONFIG_VERSION_MINOR          IRVE_CMAKE_VERSION_MINOR
#endif

#ifndef IRVE_INTERNAL_CONFIG_VERSION_PATCH
#define IRVE_INTERNAL_CONFIG_VERSION_PATCH          IRVE_CMAKE_VERSION_PATCH
#endif

#ifndef IRVE_INTERNAL_CONFIG_VERSION_STRING
#define IRVE_INTERNAL_CONFIG_VERSION_STRING         IRVE_CMAKE_VERSION_STRING
#endif

#ifndef IRVE_INTERNAL_CONFIG_BUILD_SYSTEM_STRING
#define IRVE_INTERNAL_CONFIG_BUILD_SYSTEM_STRING    IRVE_CMAKE_BUILD_SYSTEM_STRING
#endif

#ifndef IRVE_INTERNAL_CONFIG_BUILD_HOST_STRING
#define IRVE_INTERNAL_CONFIG_BUILD_HOST_STRING      IRVE_CMAKE_BUILD_HOST_STRING
#endif

#ifndef IRVE_INTERNAL_CONFIG_COMPILE_TARGET_STRING
#define IRVE_INTERNAL_CONFIG_COMPILE_TARGET_STRING  IRVE_CMAKE_COMPILE_TARGET_STRING
#endif

#ifndef IRVE_INTERNAL_CONFIG_COMPILER_STRING
#define IRVE_INTERNAL_CONFIG_COMPILER_STRING        IRVE_CMAKE_COMPILER_STRING
#endif

#ifndef IRVE_INTERNAL_CONFIG_RUST
#define IRVE_INTERNAL_CONFIG_RUST                   IRVE_CMAKE_RUST
#endif

#elif defined(IRVE_RAW_MAKEFILE_BUILDSYSTEM)

#ifndef IRVE_INTERNAL_CONFIG_BUILD_SYSTEM_STRING
#define IRVE_INTERNAL_CONFIG_BUILD_SYSTEM_STRING    "Raw Makefile"
#endif

#endif

//Defaults if not known from build system

#ifndef IRVE_INTERNAL_CONFIG_DISABLE_LOGGING
#define IRVE_INTERNAL_CONFIG_DISABLE_LOGGING        0
#endif

#ifndef IRVE_INTERNAL_CONFIG_ASYNC_LOGGING
#define IRVE_INTERNAL_CONFIG_ASYNC_LOGGING          0
#endif

#ifndef IRVE_INTERNAL_CONFIG_SANITIZE
#define IRVE_INTERNAL_CONFIG_SANITIZE               0
#endif

#ifndef IRVE_INTERNAL_CONFIG_VERSION_MAJOR
#define IRVE_INTERNAL_CONFIG_VERSION_MAJOR          0
#endif

#ifndef IRVE_INTERNAL_CONFIG_VERSION_MINOR
#define IRVE_INTERNAL_CONFIG_VERSION_MINOR          0
#endif

#ifndef IRVE_INTERNAL_CONFIG_VERSION_PATCH
#define IRVE_INTERNAL_CONFIG_VERSION_PATCH          0
#endif

#ifndef IRVE_INTERNAL_CONFIG_VERSION_STRING
#define IRVE_INTERNAL_CONFIG_VERSION_STRING         "Version Unknown"
#endif

#ifndef IRVE_INTERNAL_CONFIG_BUILD_SYSTEM_STRING
#define IRVE_INTERNAL_CONFIG_BUILD_SYSTEM_STRING    "Unknown build system"
#endif

//TODO ask the compiler itself in this case
#ifndef IRVE_INTERNAL_CONFIG_BUILD_HOST_STRING
#define IRVE_INTERNAL_CONFIG_BUILD_HOST_STRING      "Unknown"
#endif

//TODO ask the compiler itself in this case
#ifndef IRVE_INTERNAL_CONFIG_COMPILE_TARGET_STRING
#define IRVE_INTERNAL_CONFIG_COMPILE_TARGET_STRING  "Unknown"
#endif

//TODO ask the compiler itself in this case
#ifndef IRVE_INTERNAL_CONFIG_COMPILER_STRING
#define IRVE_INTERNAL_CONFIG_COMPILER_STRING        "Unknown"
#endif

#ifndef IRVE_INTERNAL_CONFIG_RUST
#define IRVE_INTERNAL_CONFIG_RUST                   0
#endif

#endif//CONFIG_H
